spring:
  application:
    name: mySpringbootProject
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/springbootsystem?useUnicode=true&characterEncoding=utf-8
    username: root
    password: '000000'
  data:
    redis:
      port: 6379
      host: localhost

server:
  port: 8081
  servlet:
    context-path: /

mybatis:
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  mapper-locations: classpath:mapper/*.xml

app:
  logging:
    enabled: true
    log-request-params: true
    log-response-body: true
    controller-log-enabled: true
    operation-log-enabled: true
# ????????????????
# spring.profiles=prod
# app.logging.log-response-body=false
logging:
  file:
    path: logs
  logback:
    rolling policy:
      max-file-size: 10MB
  level:
    root: INFO
    org.example: DEBUG